# Generated by Django 4.0.10 on 2024-07-13 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_rename_comment_comment_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
